language: python

python:
 - "2.7"
 - "3.6"

install:
 - pip install pyflakes pycodestyle
 - pip install -r requirements.txt

script:
 # Static analysis
 - pyflakes .
 - pycodestyle --statistics --count .

 # Dry run
 - python whyaretheflagsup.py --test -y whyaretheflagsup_example.yaml -i flag.jpg

matrix:
  fast_finish: true
